### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mykle1**
I changed width to  maxWidth and heigth to maxHeight in the config options and some small grammatical errors. I hope you don't mind. I love this module!

### CODE REVIEW

**Comment by roramirez** [comment]
Great!, which one of all Pull Request is valid? 

Also, it is need change the variable into the module not only the README and add backward compatibility for behavior of the configuration.

**Comment by roramirez** [comment]
Sorry @mykle1 

All this is my mistake. I can see your Pull Request is OK. I was thinking the option in module is called like width and heigth.  

This close #1 

Thanks @mykle1

**Comment by mykle1** [comment]
On 3/15/2017 5:21 PM, Rodrigo Ramírez Norambuena wrote:

> Great!, which one of all Pull Request is valid?
>
The last one. Sorry about that. I was having some issues with my 
computer when I was editing so I didn't know if the edits were going 
through. So the last pull request is the correct one.
>
> Also, it is need change the variable into the module not only the 
> README and add backward compatibility for behavior of the configuration.
>
The module does not need to be changed. The module works with my 
changes, maxWidth: and maxHeight: in the config.js.  -  maxWidth: 
"100%", and maxHeight: "100%", are already set in the main js file.

Only the readMe was incorrect.

Thank you

Mykle

**Comment by mykle1** [comment]
Oh, I just sent you an email.

Thanks for the wonderful module!

Mykle

**Comment by cowboysdude** [comment]
Thanks for a great catch guys!

**Comment by roramirez** [comment]
Merged!

**Comment by mykle1** [comment]
Cool, thanks!

**Pull request merged**
